// Naplní databázu reálnymi otvorenými výzvami (fakty k 5. 7. 2026).
// Kde verejný zdroj neuvádza vyhlasovateľa, je provider NULL — na webe sa
// zobrazí „uvedený v dokumentácii výzvy“. Žiadne vymyslené údaje.

const { pool, init } = require('./db');

const VYZVY = [
  {
    slug: 'zelene-projekty-mesta-obce-2026',
    title: 'Zelené projekty pre mestá a obce',
    provider: null,
    program: 'Schéma umožňuje partnerstvo s nórskymi subjektmi',
    category: 'Ochrana životného prostredia',
    applicants: 'samospráva',
    regions: 'Celé Slovensko',
    amount_max: 10000,
    deadline: '2026-08-05',
    summary: 'Výsadba zelene, revitalizácia verejných priestranstiev a vodozádržné opatrenia v mestách a obciach. Miera podpory až 100 %.',
    details: 'Podporené budú projekty zamerané na výsadbu drevín a zelene v intraviláne, revitalizáciu verejných priestranstiev a realizáciu vodozádržných opatrení ako reakciu na zmenu klímy. Projekty môžu byť realizované v partnerstve s nórskymi subjektmi.',
  },
  {
    slug: 'podpora-startupov-expanzia-2026',
    title: 'Podpora rozvoja startupov od začiatku až po expanziu do zahraničia',
    provider: null,
    program: null,
    category: 'Rozvoj podnikania',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    deadline: '2026-09-14',
    summary: 'Podpora startupov vo všetkých fázach životného cyklu vrátane expanzie na zahraničné trhy.',
    details: 'Program pokrýva celý životný cyklus startupu — od validácie nápadu cez rast až po vstup na zahraničné trhy.',
  },
  {
    slug: 'climatetech-akcelerator-2026',
    title: 'Akcelerátor pre ClimateTech startupy zo strednej Európy',
    provider: null,
    program: 'Súkromný akceleračný program',
    category: 'Rozvoj podnikania',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    deadline: '2026-07-19',
    summary: 'Akceleračný program pre startupy z regiónu strednej Európy, ktoré vyvíjajú klimatické technológie.',
    details: 'Program je určený pre startupy zo strednej Európy vrátane Slovenska, ktoré pracujú na riešeniach v oblasti klimatických technológií.',
  },
  {
    slug: 'bilateralne-iniciativy-oos-2026',
    title: 'Grant na bilaterálne iniciatívy pre organizácie občianskej spoločnosti',
    provider: null,
    program: 'Bilaterálny fond',
    category: 'Rozvoj podnikania',
    applicants: 'mimovládne organizácie',
    regions: 'Celé Slovensko',
    amount_max: 25000,
    deadline: '2026-08-31',
    summary: 'Bilaterálna spolupráca organizácií občianskej spoločnosti so zahraničnými partnermi. Miera podpory 100 %.',
    details: 'Podpora spoločných iniciatív slovenských občianskych organizácií a zahraničných partnerov — výmena skúseností, spoločné podujatia a budovanie partnerstiev.',
  },
  {
    slug: 'cloudove-kredity-startupy-2026',
    title: 'Cloudové kredity až do 350 000 USD pre startupy',
    provider: null,
    program: 'Program poskytovateľa cloudových služieb',
    category: 'Digitalizácia a IT',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    deadline: null,
    deadline_note: 'priebežne',
    summary: 'Nefinančná podpora vo forme kreditov na cloudovú infraštruktúru pre startupy, až do výšky 350 000 USD.',
    details: 'Startupy môžu získať kredity na cloudové služby (infraštruktúra, AI nástroje). Nejde o dotáciu, ale o vecné plnenie bez nároku na podiel vo firme.',
  },
  {
    slug: 'ai-startup-program-2026',
    title: 'Bezplatný globálny program pre AI startupy',
    provider: null,
    program: 'Program technologickej spoločnosti',
    category: 'Digitalizácia a IT',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    deadline: null,
    deadline_note: 'priebežne',
    summary: 'Bezplatný akceleračný a podporný program pre firmy vyvíjajúce riešenia založené na umelej inteligencii.',
    details: 'Globálny program pre AI startupy — mentoring, technická podpora a prístup k nástrojom. Účasť je bezplatná.',
  },
  {
    slug: 'stabilny-rozvoj-obcianskych-organizacii-2026',
    title: 'Grant pre stabilný rozvoj občianskych organizácií na Slovensku',
    provider: null,
    program: null,
    category: 'Sociálne služby a zdravotníctvo',
    applicants: 'mimovládne organizácie',
    regions: 'Celé Slovensko',
    amount_max: 120000,
    deadline: '2026-09-11',
    summary: 'Inštitucionálny a organizačný rozvoj občianskych organizácií — dlhodobá stabilita namiesto projektového financovania.',
    details: 'Výzva podporuje inštitucionálny rozvoj — strategické plánovanie, rozvoj tímu, diverzifikáciu financovania a budovanie kapacít organizácií občianskej spoločnosti.',
  },
  {
    slug: 'sluzby-pre-zeny-nasilie-2026',
    title: 'Rozširovanie špecializovaných služieb pre ženy zažívajúce domáce a rodovo podmienené násilie',
    provider: null,
    program: null,
    category: 'Sociálne služby a zdravotníctvo',
    applicants: 'podnikatelia, samospráva, mimovládne organizácie',
    regions: 'Celé Slovensko',
    amount_max: 700000,
    deadline: '2026-10-10',
    summary: 'Poradenské centrá, bezpečné bývanie, terénne služby a programy pre pôvodcov násilia. Miera podpory 100 %.',
    details: 'Podpora rozširovania špecializovaných služieb: poradenské centrá, bezpečné ubytovanie, terénna práca a intervenčné programy.',
  },
  {
    slug: 'regionalne-kulturne-podujatia-2026',
    title: 'Granty na regionálne kultúrne podujatia a rozvoj kultúrnych organizácií mimo Bratislavy',
    provider: null,
    program: null,
    category: 'Kultúra, cestovný ruch a šport',
    applicants: 'mimovládne organizácie',
    regions: 'Trnavský kraj, Trenčiansky kraj, Nitriansky kraj, Žilinský kraj, Banskobystrický kraj, Prešovský kraj, Košický kraj',
    amount_max: 12000,
    deadline: '2026-07-08',
    summary: 'Festivaly, koncerty, divadlo a komunitná kultúra vo všetkých krajoch okrem Bratislavského. Podpora až 100 %.',
    details: 'Výzva podporuje regionálne kultúrne podujatia a rozvoj kultúrnych organizácií pôsobiacich mimo hlavného mesta.',
  },
  {
    slug: 'mladi-polnohospodari-investicie-2026',
    source_url: 'https://www.apa.sk',
    title: 'Investície pre mladých poľnohospodárov',
    provider: 'Pôdohospodárska platobná agentúra (PPA)',
    program: 'Strategický plán SPP 2023 – 2027',
    category: 'Pôdohospodárstvo a lesníctvo',
    applicants: 'podnikatelia, jednotlivci',
    regions: 'Celé Slovensko',
    deadline: '2026-09-11',
    summary: 'Modernizácia fariem mladých poľnohospodárov — technológie, digitalizácia a energetická efektívnosť.',
    details: 'Investičná podpora pre mladých poľnohospodárov na celom území SR: nákup technológií, digitalizácia výroby a opatrenia na zvýšenie energetickej efektívnosti.',
  },
  {
    slug: 'socialne-taxiky-aed-obce-2026',
    source_url: 'https://www.health.gov.sk',
    title: 'Dotácia na sociálne taxíky a AED pre obce',
    provider: 'Ministerstvo zdravotníctva SR',
    program: 'Alokácia približne 2 mil. €',
    category: 'Sociálne služby a zdravotníctvo',
    applicants: 'samospráva',
    regions: 'Prešovský kraj, Košický kraj, Banskobystrický kraj, Žilinský kraj',
    amount_min: 40000,
    amount_max: 95000,
    allocation: 2000000,
    deadline: '2026-08-19',
    summary: 'Nízkoemisné vozidlá na prepravu seniorov za zdravotnou starostlivosťou a verejne dostupné defibrilátory (AED). Miera podpory 95 %.',
    details: 'Výzva pre 21 určených obcí (centrá zdieľaných služieb, minimálne 3 obce v centre). Financuje nízkoemisné vozidlá na prepravu seniorov a osôb so zníženou mobilitou a nákup automatických externých defibrilátorov.',
  },
  {
    slug: 'pokrocile-materialy-vyroba-2026',
    title: 'Modernizácia výroby pokročilých materiálov',
    provider: null,
    program: null,
    category: 'Veda a výskum',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    amount_max: 60000,
    deadline: '2026-07-06',
    summary: 'Zelené a digitálne výrobné procesy, rozšírenie kapacít a inteligentné senzory vo výrobe pokročilých materiálov. Podpora 75 %.',
    details: 'Výzva pre výrobcov pokročilých materiálov na zavádzanie zelených a digitálnych výrobných procesov, rozširovanie kapacít a nasadenie inteligentných senzorov.',
  },
  {
    slug: 'polnohospodarstvo-technologie-digitalizacia-2026',
    source_url: 'https://www.apa.sk',
    title: 'Nové technológie a digitalizácia poľnohospodárskej prvovýroby',
    provider: 'Pôdohospodárska platobná agentúra (PPA)',
    program: 'Strategický plán SPP 2023 – 2027',
    category: 'Pôdohospodárstvo a lesníctvo',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    amount_max: 600000,
    deadline: '2026-08-14',
    summary: 'Nové technológie, digitalizácia a energetická efektívnosť vrátane OZE v poľnohospodárskej prvovýrobe.',
    details: 'Podpora poľnohospodárskych podnikov pri zavádzaní nových technológií, digitalizácii prvovýroby a investíciách do energetickej efektívnosti vrátane obnoviteľných zdrojov energie.',
  },
  {
    slug: 'zelena-podnikom-2026',
    source_url: 'https://zelenapodnikom.sk',
    title: 'Zelená podnikom — obnoviteľné zdroje pre firmy',
    provider: 'Slovenská inovačná a energetická agentúra (SIEA)',
    program: 'Alokácia 66 mil. €',
    category: 'Energetika a OZE',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    amount_max: 50000,
    allocation: 66000000,
    deadline: null,
    deadline_note: 'pokračovanie ohlásené na rok 2026',
    summary: 'Poukážky na fotovoltiku, tepelné čerpadlá a ďalšie obnoviteľné zdroje energie pre podniky, do 50 000 € na firmu.',
    details: 'Národný projekt SIEA poskytuje podnikom poukážky na inštaláciu zariadení na využívanie obnoviteľných zdrojov energie — fotovoltické panely, tepelné čerpadlá a ďalšie.',
  },
  {
    slug: 'inovacne-poukazky-robotizacia-2026',
    source_url: 'https://www.siea.sk',
    title: 'Inovačné poukážky na robotizáciu a automatizáciu v priemysle',
    provider: 'Slovenská inovačná a energetická agentúra (SIEA)',
    program: null,
    category: 'Rozvoj podnikania',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    amount_min: 3000,
    amount_max: 30000,
    deadline: null,
    deadline_note: 'otvorená od januára 2026',
    summary: 'Poukážky 3 000 – 30 000 € na robotizáciu, automatizáciu a riešenia Industry 4.0, miera podpory až 85 %.',
    details: 'Inovačné poukážky pokrývajú nákup softvéru a hardvéru pre robotizáciu, automatizáciu výroby a zavádzanie prvkov Industry 4.0.',
  },
  {
    slug: 'vouchery-zahranicne-veltrhy-2026',
    title: 'Voucherová podpora účasti na zahraničných veľtrhoch a výstavách',
    provider: null,
    program: null,
    category: 'Rozvoj podnikania',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    deadline: null,
    deadline_note: 'ohlásená od marca 2026',
    summary: 'Spolufinancovanie účasti mikro, malých a stredných podnikov na zahraničných veľtrhoch a výstavách formou voucherov.',
    details: 'Voucherová schéma pre MSP na pokrytie nákladov spojených s vystavovaním na zahraničných veľtrhoch a výstavách.',
  },
  {
    slug: 'ai-robotika-vyroba-horizont-2026',
    source_url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/',
    title: 'Aplikácia AI a robotiky vo výrobe (kaskádová výzva)',
    provider: 'Európska komisia — Horizont Európa (kaskádové financovanie)',
    program: 'Horizont Európa',
    category: 'Veda a výskum',
    applicants: 'podnikatelia',
    regions: 'Celé Slovensko',
    amount_max: 200000,
    deadline: null,
    deadline_note: 'podľa jednotlivých kôl výzvy',
    summary: 'Až 200 000 € na projekty AI robotiky na detekciu chýb vo výrobe — 70 % pre MSP, 100 % pre startupy, projekty do 12 mesiacov.',
    details: 'Kaskádová výzva programu Horizont Európa pre MSP a startupy z EÚ. Podporené budú projekty nasadenia robotiky riadenej umelou inteligenciou na detekciu defektov vo výrobných procesoch.',
  },
  {
    slug: 'cirkularna-ekonomika-reuse-centra-2026',
    title: 'Cirkulárna ekonomika — centrá opätovného použitia',
    provider: null,
    program: 'Alokácia 4,8 mil. €',
    category: 'Ochrana životného prostredia',
    applicants: 'samospráva, mimovládne organizácie',
    regions: 'Celé Slovensko',
    allocation: 4800000,
    deadline: null,
    deadline_note: 'ohlásená v 1. kvartáli 2026',
    summary: 'Zriaďovanie centier opätovného použitia a predchádzanie vzniku odpadov, v partnerstve samospráv a neziskového sektora.',
    details: 'Výzva podporí vznik centier opätovného použitia (reuse centier) a aktivity predchádzania vzniku odpadov. Žiadať môžu samosprávy a neziskový sektor, aj v partnerstve s podnikmi.',
  },
];

async function seed() {
  await init();
  // Bez overeného oficiálneho odkazu výzvu nezakladáme — žiadne nepodložené položky
  for (const v of VYZVY.filter((x) => x.source_url)) {
    await pool.query(
      `INSERT INTO vyzvy (slug, title, provider, program, category, applicants, regions,
                          amount_min, amount_max, allocation, deadline, deadline_note,
                          summary, details, source_url, status)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'otvorena')
       ON CONFLICT (slug) DO UPDATE SET
         title = EXCLUDED.title, provider = EXCLUDED.provider, program = EXCLUDED.program,
         category = EXCLUDED.category, applicants = EXCLUDED.applicants, regions = EXCLUDED.regions,
         amount_min = EXCLUDED.amount_min, amount_max = EXCLUDED.amount_max,
         allocation = EXCLUDED.allocation, deadline = EXCLUDED.deadline,
         deadline_note = EXCLUDED.deadline_note, summary = EXCLUDED.summary,
         details = EXCLUDED.details, source_url = EXCLUDED.source_url`,
      [v.slug, v.title, v.provider, v.program, v.category, v.applicants, v.regions,
       v.amount_min ?? null, v.amount_max ?? null, v.allocation ?? null,
       v.deadline ?? null, v.deadline_note ?? null, v.summary, v.details ?? null,
       v.source_url ?? null]
    );
  }
  console.log(`Seed hotový: ${VYZVY.length} výziev.`);
  await pool.end();
}

seed().catch((e) => { console.error(e); process.exit(1); });
